# Generated by Django 5.0.6 on 2024-08-14 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subject_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_subject_code', to='api.subject'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('pass_fail', models.BooleanField()),
                ('comments', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_student', to=settings.AUTH_USER_MODEL)),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_subject_code', to='api.subject')),
            ],
        ),
    ]
