# Generated by Django 5.0.6 on 2024-08-14 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_attendance_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('maximum_score', models.IntegerField()),
                ('pass_fail', models.BooleanField()),
                ('comments', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_student', to=settings.AUTH_USER_MODEL)),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_subject_code', to='api.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
