# Generated by Django 5.0.6 on 2024-08-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_attendance_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
